language: node_js
node_js: stable
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "fanjames"
- git config --global user.email "fanhuajames@gmail.com"
- npm install -g hexo-cli
- export HEXO_DEPLOYER_REPO=https://$REPO_TOKEN@github.com/fanjames/blog.git
install:
- npm i
script:
- hexo clean
- hexo generate
- hexo deploy
